### ISSUE TITLE
BoM list

### ISSUE THREAD

**Issue by hildogjr** [OpenElectronicsLab/OpenHardwareExG#2]
Missing some BoM list with the part number to make easy the purchase procedure.

**Comment by ericherman** [comment]
You can see a number of ".bom" files in the project. Probably you're interested in the main board, with the analog+digital patch shields:

 * https://github.com/OpenElectronicsLab/OpenHardwareExG/blob/master/kicad-files/rev1/arduino-ads129x.bom
 * https://github.com/OpenElectronicsLab/OpenHardwareExG/blob/master/kicad-files/rev1/patch-shield-analog.bom
 * https://github.com/OpenElectronicsLab/OpenHardwareExG/blob/master/kicad-files/rev1/patch-shield-digital.bom

Since there are multiple boards, we made a "combined mouser bom" for the patch-shield version for ordering from mouser:
 * https://github.com/OpenElectronicsLab/OpenHardwareExG/blob/master/kicad-files/rev1/combined.mouser.bom

However, not all parts were available from mouser at the time, as such we created a 4ucon bom:
 * https://github.com/OpenElectronicsLab/OpenHardwareExG/blob/master/kicad-files/rev1/4ucon.bom

Additionally, for the touch-proof panel mount jacks, we found them at DiscountDisposables as documented in:
 * https://github.com/OpenElectronicsLab/OpenHardwareExG/blob/master/kicad-files/rev1/fasteners.txt

I hope this is helpful for you.

**Comment by hildogjr** [comment]
Thanks
